import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: ['./src/pages/**/*.{js,ts,jsx,tsx,mdx}', './src/components/**/*.{js,ts,jsx,tsx,mdx}', './src/app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1280px',
    },
    fontSize: {
      min: ['12px', { lineHeight: '18px' }],
      sm: ['14px', { lineHeight: '20px' }],
      md: ['16px', { lineHeight: '24px' }],
      lg: ['18px', { lineHeight: '28px' }],
      max: ['20px', { lineHeight: '32px' }],
      max1: ['22px', { lineHeight: '36px' }],
      max2: ['24px', { lineHeight: '40px' }],
    },
    zIndex: {
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
      auto: 'auto',
    },
    fontWeight: {
      hairline: '100',
      thin: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    boxShadow: {
      cardShow: '0px 13px 40px 0px rgba(75, 102, 135, 0.10);',
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      health: '#1ED760',
      society: '#C167FD',
      crime: '#F3408E',
      active: '#EC6630',
      religion: '#776BE5',
      bgGray: '#F0F0F0',
      bgDark: '#242424',
      borderb: '#E8EDF1',
      gray: {
        '100': '#999',
        '200': '#898989',
        '300': '#BEBEBE',
        '900': '#1a202c',
        '1000': '#F0F0F0',
      },
      fontGry: {
        '100': '#B4B4B4',
        '600': '#646464',
        c8: '#C8C8C8',
        dark9b: '#9B9B9B',
      },
      play: '#FF5A0F',
      hbg: '#f5f5f5',
      homehbg: '#dcdcdc',
      darkHomeBg: '#404040',
      e8e: '#E8EDF1',
    },
    borderRadius: {
      none: '0',
      sm: '.125rem',
      DEFAULT: '.25rem',
      lg: '.5rem',
      xl: '1rem',
      round: '50%',
      full: '9999px',
      '10px': '10px',
      '5px': '5px',
      1: '1px',
    },
    spacing: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '7': '1.75rem',
      '8': '2rem',
      '9': '2.25rem',
      '10': '2.5rem',
      '11': '2.75rem',
      '12': '3rem',
      '14': '3.5rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '28': '7rem',
      '32': '8rem',
      '36': '9rem',
      '40': '10rem',
      '44': '11rem',
      '48': '12rem',
      '52': '13rem',
      '56': '14rem',
      '60': '15rem',
      '64': '16rem',
      '72': '18rem',
      '80': '20rem',
      '96': '24rem',
      '100': '100%',
      '111': '400px',
      '1280': '1280px',
      px: '1px',
      '0.5': '0.125rem',
      '1.5': '0.375rem',
      '2.5': '0.625rem',
      '3.5': '0.875rem',
      '24px': '24px',
    },
    opacity: {
      '0': '0',
      '20': '0.2',
      '40': '0.4',
      '60': '0.6',
      '80': '0.8',
      '100': '1',
    },
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        darkTheme: {
          '100': '#1E1E1E',
          '200': '#2A2A2A',
          '300': '#3A3A3A',
          '400': '#4A4A4A',
          '500': '#5A5A5A',
          '600': '#6A6A6A',
          '700': '#7A7A7A',
          '800': '#8A8A8A',
          '900': '#9A9A9A',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'scroll-x': 'linear scroll-x 60s infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
  async rewrites() {
    return [
      {
        source: '/api/:path*', // 配置代理的路径
        destination: 'https://pfx.vpixl.com/:path*', // 目标服务器地址
      },
    ]
  },
}
export default config
