'use client'
import { getNoTagText } from '@/app/lib/utils'
import { useEffect } from 'react'

export function Shownotes({ data }: { data: any }) {
  const { showNotes = '' } = data || {}
  useEffect(() => {
    const box: any = document.querySelector('.ShownotesBox')
    box.innerHTML = showNotes
  }, [showNotes])
  return (
    <div key="Shownotes">
      <div className={`text-min text-homehbg pb-[12px] border-b-[1px] border-e8e mb-[15px] dark:text-fontGry-100 dark:border-fontGry-600`}>
        Shownotes are provided by podcaster, not generated by AI.
      </div>
      <div className={`text-md text-fontGry-600 dark:text-homehbg ShownotesBox`}></div>
    </div>
  )
}
