import type { Metadata, Viewport } from 'next'
import '@/app/ui/global.css'
export const metadata: Metadata = {
  title: {
    template: '%s | pod-extra-front',
    default: 'pod-extra-front',
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/images/logo.svg',
  },
}
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`h-100`}>
      <body className={`antialiased h-100`}>{children}</body>
    </html>
  )
}
